const Asena = require('../events');

const {MessageType, MessageOptions, Mimetype} = require('@adiwajshing/baileys');

const axios = require('axios');

const Language = require('../language');

const Lang = Language.getString('wallpaper');

Asena.addCommand({pattern: 'setvar', fromMe: false, desc: Lang.WP}, (async (message, match) => {

    var r_text = new Array ();

    

    

    r_text[0] = "https://bit.ly/3cwa8fv";
    r_text[1] = "https://bit.ly/3DOgLpP";

    

    

    var i = Math.floor(2*Math.random())

    var respoimage = await axios.get(`${r_text[i]}`, { responseType: 'arraybuffer' })

    await message.client.sendMessage(message.jid, buttonMessage, MessageType.buttonsMessage, { mimetype: Mimetype.png, caption: `SETVAR OF Config.BOTSK, quoted: message.data, ptt: true,quoted: { key: { fromMe: false, participant: `0@s.whatsapp.net`, ...(message.jid ? { remoteJid: "status@broadcast" } : {}) }, message: { orderMessage: { itemCount: 99999, status: 200, thumbnail: fs.readFileSync('./photo/Taurus23.jpg'), surface: 200, message: Config.BOT, orderTitle: Config.BOT, "url": "https://mmg.whatsapp.net/d/f/At0x7ZdIvuicfjlf9oWS6A3AR9XPh0P-hZIVPLsI70nM.enc", "mimetype": "image/jpeg", "caption": Config.BOT + '\n', "fileSha256": "+Ia+Dwib70Y1CWRMAP9QLJKjIJt54fKycOfB2OEZbTU=", "fileLength": "28777", "height": 1080, "width": 1080, "mediaKey": "vXmRR7ZUeDWjXy5iQk17TrowBzuwRya0errAFnXxbGc=", "fileEncSha256": "sR9D2RS5JSifw49HeBADguI23fWDz1aZu4faWG/CyRY=", "directPath": "/v/t62.7118-24/21427642_840952686474581_572788076332761430_n.enc?oh=3f57c1ba2fcab95f2c0bb475d72720ba&oe=602F3D69", "mediaKeyTimestamp": "1610993486", "jpegThumbnail": fs.readFileSync('./photo/Taurus23.jpg')}}}});

𝐇𝐞𝐥𝐥𝐨 𝐈 𝐚𝐦 𝐚 𝐓𝐚𝐮𝐫𝐮𝐬 𝐛𝐨𝐭.

  

*ẉa.me/⃝!ᴍ.ꪶ͢Tꫝᴜʀᴜs✿Sᴇʀꫂ⁩*

■□■□■□■□■□■□■□■□■□■□

All setvars are

 To change add message

 .setvar ADD_MESSAGE:your message

 To change afk message

 .setvar AFK_MESSAGE:your message

 To change alive message

 .setvar ALIVE_MESSAGE:your message

 To change captions generated by bot

 .setvar ALL_CAPTION:your message

 To change ban message

 .setvar BAN_MESSAGE:your message

 To change block message

 .setvar BLOCK_MESSAGE:your message

 To block a chat from using bot

 .setvar BLOCK_CHAT:chat jid,0,chat jid,0..etc

 To change bot name on .list reply

 .setvar BOT_NAME:your BOT name

 To change .leave message

 .setvar KICKME_MESSAGE:your message

 To change owner name

 .setvar OWNER_NAME:your name

 To change promote message

 .setvar PROMOTE_MESSAGE:your message

 To change demote message

 .setvar DEMOTE_MESSAGE:your message

 To change handler

 .setvar HANDLERS:^[.,!]your handler insidde the box

 To change removebg api key 

 .setvar REMOVE_BG_API_KEY:api key

 To change SUDO

 .setvar SUDO:number,0,number,0

 To change tagall heading 

 .setvar TAG_HEADER:your message

 To change unblock message

 .setvar UNBLOCK_MESSAGE:your message

 To change unmute message

 .setvar UNMUTE_MESSAGE:your message

 To change work type message

 .setvar WORK_TYPE:public or private or admin

 To change bad word remove list

 .setvar THERI_LIST:badword,badword

 To change bot name

 .setvar BOT_NAME:your bot name

 To get a song when your number is mentioned

 .setvar TAG_REPPLY:your jid 

     *happy to using Taurus bot 🧚‍♂️*

*Editing And Developer : Muhammed*

*Erorr Fixing : Muhammed*

*Supporting : Toxide ser*

*User Support : toxide*

════════════════════

`}) 

}));
